/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedVaultRouteImport } from './routes/_authed/vault'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedServiceAccountsIndexRouteImport } from './routes/_authed/service-accounts/index'
import { Route as AuthedOauth2IndexRouteImport } from './routes/_authed/oauth2/index'
import { Route as AuthedIdentitiesIndexRouteImport } from './routes/_authed/identities/index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups/index'
import { Route as AuthedServiceAccountsCreateRouteImport } from './routes/_authed/service-accounts/create'
import { Route as AuthedServiceAccountsAccountIdRouteImport } from './routes/_authed/service-accounts/$accountId'
import { Route as AuthedOauth2CreateRouteImport } from './routes/_authed/oauth2/create'
import { Route as AuthedOauth2ClientIdRouteImport } from './routes/_authed/oauth2/$clientId'
import { Route as AuthedIdentitiesImportRouteImport } from './routes/_authed/identities/import'
import { Route as AuthedIdentitiesCreateRouteImport } from './routes/_authed/identities/create'
import { Route as AuthedIdentitiesPersonIdRouteImport } from './routes/_authed/identities/$personId'
import { Route as AuthedGroupsCreateRouteImport } from './routes/_authed/groups/create'
import { Route as AuthedGroupsGroupIdRouteImport } from './routes/_authed/groups/$groupId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVaultRoute = AuthedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServiceAccountsIndexRoute =
  AuthedServiceAccountsIndexRouteImport.update({
    id: '/service-accounts/',
    path: '/service-accounts/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOauth2IndexRoute = AuthedOauth2IndexRouteImport.update({
  id: '/oauth2/',
  path: '/oauth2/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdentitiesIndexRoute = AuthedIdentitiesIndexRouteImport.update({
  id: '/identities/',
  path: '/identities/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServiceAccountsCreateRoute =
  AuthedServiceAccountsCreateRouteImport.update({
    id: '/service-accounts/create',
    path: '/service-accounts/create',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedServiceAccountsAccountIdRoute =
  AuthedServiceAccountsAccountIdRouteImport.update({
    id: '/service-accounts/$accountId',
    path: '/service-accounts/$accountId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOauth2CreateRoute = AuthedOauth2CreateRouteImport.update({
  id: '/oauth2/create',
  path: '/oauth2/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOauth2ClientIdRoute = AuthedOauth2ClientIdRouteImport.update({
  id: '/oauth2/$clientId',
  path: '/oauth2/$clientId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdentitiesImportRoute = AuthedIdentitiesImportRouteImport.update({
  id: '/identities/import',
  path: '/identities/import',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdentitiesCreateRoute = AuthedIdentitiesCreateRouteImport.update({
  id: '/identities/create',
  path: '/identities/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdentitiesPersonIdRoute =
  AuthedIdentitiesPersonIdRouteImport.update({
    id: '/identities/$personId',
    path: '/identities/$personId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsCreateRoute = AuthedGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsGroupIdRoute = AuthedGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/audit': typeof AuthedAuditRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/vault': typeof AuthedVaultRoute
  '/groups/$groupId': typeof AuthedGroupsGroupIdRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/identities/$personId': typeof AuthedIdentitiesPersonIdRoute
  '/identities/create': typeof AuthedIdentitiesCreateRoute
  '/identities/import': typeof AuthedIdentitiesImportRoute
  '/oauth2/$clientId': typeof AuthedOauth2ClientIdRoute
  '/oauth2/create': typeof AuthedOauth2CreateRoute
  '/service-accounts/$accountId': typeof AuthedServiceAccountsAccountIdRoute
  '/service-accounts/create': typeof AuthedServiceAccountsCreateRoute
  '/groups/': typeof AuthedGroupsIndexRoute
  '/identities/': typeof AuthedIdentitiesIndexRoute
  '/oauth2/': typeof AuthedOauth2IndexRoute
  '/service-accounts/': typeof AuthedServiceAccountsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/audit': typeof AuthedAuditRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/vault': typeof AuthedVaultRoute
  '/groups/$groupId': typeof AuthedGroupsGroupIdRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/identities/$personId': typeof AuthedIdentitiesPersonIdRoute
  '/identities/create': typeof AuthedIdentitiesCreateRoute
  '/identities/import': typeof AuthedIdentitiesImportRoute
  '/oauth2/$clientId': typeof AuthedOauth2ClientIdRoute
  '/oauth2/create': typeof AuthedOauth2CreateRoute
  '/service-accounts/$accountId': typeof AuthedServiceAccountsAccountIdRoute
  '/service-accounts/create': typeof AuthedServiceAccountsCreateRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/identities': typeof AuthedIdentitiesIndexRoute
  '/oauth2': typeof AuthedOauth2IndexRoute
  '/service-accounts': typeof AuthedServiceAccountsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/vault': typeof AuthedVaultRoute
  '/_authed/groups/$groupId': typeof AuthedGroupsGroupIdRoute
  '/_authed/groups/create': typeof AuthedGroupsCreateRoute
  '/_authed/identities/$personId': typeof AuthedIdentitiesPersonIdRoute
  '/_authed/identities/create': typeof AuthedIdentitiesCreateRoute
  '/_authed/identities/import': typeof AuthedIdentitiesImportRoute
  '/_authed/oauth2/$clientId': typeof AuthedOauth2ClientIdRoute
  '/_authed/oauth2/create': typeof AuthedOauth2CreateRoute
  '/_authed/service-accounts/$accountId': typeof AuthedServiceAccountsAccountIdRoute
  '/_authed/service-accounts/create': typeof AuthedServiceAccountsCreateRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/identities/': typeof AuthedIdentitiesIndexRoute
  '/_authed/oauth2/': typeof AuthedOauth2IndexRoute
  '/_authed/service-accounts/': typeof AuthedServiceAccountsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/unauthorized'
    | '/audit'
    | '/dashboard'
    | '/vault'
    | '/groups/$groupId'
    | '/groups/create'
    | '/identities/$personId'
    | '/identities/create'
    | '/identities/import'
    | '/oauth2/$clientId'
    | '/oauth2/create'
    | '/service-accounts/$accountId'
    | '/service-accounts/create'
    | '/groups/'
    | '/identities/'
    | '/oauth2/'
    | '/service-accounts/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/unauthorized'
    | '/audit'
    | '/dashboard'
    | '/vault'
    | '/groups/$groupId'
    | '/groups/create'
    | '/identities/$personId'
    | '/identities/create'
    | '/identities/import'
    | '/oauth2/$clientId'
    | '/oauth2/create'
    | '/service-accounts/$accountId'
    | '/service-accounts/create'
    | '/groups'
    | '/identities'
    | '/oauth2'
    | '/service-accounts'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/callback'
    | '/login'
    | '/unauthorized'
    | '/_authed/audit'
    | '/_authed/dashboard'
    | '/_authed/vault'
    | '/_authed/groups/$groupId'
    | '/_authed/groups/create'
    | '/_authed/identities/$personId'
    | '/_authed/identities/create'
    | '/_authed/identities/import'
    | '/_authed/oauth2/$clientId'
    | '/_authed/oauth2/create'
    | '/_authed/service-accounts/$accountId'
    | '/_authed/service-accounts/create'
    | '/_authed/groups/'
    | '/_authed/identities/'
    | '/_authed/oauth2/'
    | '/_authed/service-accounts/'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/vault': {
      id: '/_authed/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthedVaultRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/service-accounts/': {
      id: '/_authed/service-accounts/'
      path: '/service-accounts'
      fullPath: '/service-accounts/'
      preLoaderRoute: typeof AuthedServiceAccountsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oauth2/': {
      id: '/_authed/oauth2/'
      path: '/oauth2'
      fullPath: '/oauth2/'
      preLoaderRoute: typeof AuthedOauth2IndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/identities/': {
      id: '/_authed/identities/'
      path: '/identities'
      fullPath: '/identities/'
      preLoaderRoute: typeof AuthedIdentitiesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/service-accounts/create': {
      id: '/_authed/service-accounts/create'
      path: '/service-accounts/create'
      fullPath: '/service-accounts/create'
      preLoaderRoute: typeof AuthedServiceAccountsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/service-accounts/$accountId': {
      id: '/_authed/service-accounts/$accountId'
      path: '/service-accounts/$accountId'
      fullPath: '/service-accounts/$accountId'
      preLoaderRoute: typeof AuthedServiceAccountsAccountIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oauth2/create': {
      id: '/_authed/oauth2/create'
      path: '/oauth2/create'
      fullPath: '/oauth2/create'
      preLoaderRoute: typeof AuthedOauth2CreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oauth2/$clientId': {
      id: '/_authed/oauth2/$clientId'
      path: '/oauth2/$clientId'
      fullPath: '/oauth2/$clientId'
      preLoaderRoute: typeof AuthedOauth2ClientIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/identities/import': {
      id: '/_authed/identities/import'
      path: '/identities/import'
      fullPath: '/identities/import'
      preLoaderRoute: typeof AuthedIdentitiesImportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/identities/create': {
      id: '/_authed/identities/create'
      path: '/identities/create'
      fullPath: '/identities/create'
      preLoaderRoute: typeof AuthedIdentitiesCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/identities/$personId': {
      id: '/_authed/identities/$personId'
      path: '/identities/$personId'
      fullPath: '/identities/$personId'
      preLoaderRoute: typeof AuthedIdentitiesPersonIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/create': {
      id: '/_authed/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AuthedGroupsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$groupId': {
      id: '/_authed/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthedGroupsGroupIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedVaultRoute: typeof AuthedVaultRoute
  AuthedGroupsGroupIdRoute: typeof AuthedGroupsGroupIdRoute
  AuthedGroupsCreateRoute: typeof AuthedGroupsCreateRoute
  AuthedIdentitiesPersonIdRoute: typeof AuthedIdentitiesPersonIdRoute
  AuthedIdentitiesCreateRoute: typeof AuthedIdentitiesCreateRoute
  AuthedIdentitiesImportRoute: typeof AuthedIdentitiesImportRoute
  AuthedOauth2ClientIdRoute: typeof AuthedOauth2ClientIdRoute
  AuthedOauth2CreateRoute: typeof AuthedOauth2CreateRoute
  AuthedServiceAccountsAccountIdRoute: typeof AuthedServiceAccountsAccountIdRoute
  AuthedServiceAccountsCreateRoute: typeof AuthedServiceAccountsCreateRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
  AuthedIdentitiesIndexRoute: typeof AuthedIdentitiesIndexRoute
  AuthedOauth2IndexRoute: typeof AuthedOauth2IndexRoute
  AuthedServiceAccountsIndexRoute: typeof AuthedServiceAccountsIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedVaultRoute: AuthedVaultRoute,
  AuthedGroupsGroupIdRoute: AuthedGroupsGroupIdRoute,
  AuthedGroupsCreateRoute: AuthedGroupsCreateRoute,
  AuthedIdentitiesPersonIdRoute: AuthedIdentitiesPersonIdRoute,
  AuthedIdentitiesCreateRoute: AuthedIdentitiesCreateRoute,
  AuthedIdentitiesImportRoute: AuthedIdentitiesImportRoute,
  AuthedOauth2ClientIdRoute: AuthedOauth2ClientIdRoute,
  AuthedOauth2CreateRoute: AuthedOauth2CreateRoute,
  AuthedServiceAccountsAccountIdRoute: AuthedServiceAccountsAccountIdRoute,
  AuthedServiceAccountsCreateRoute: AuthedServiceAccountsCreateRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
  AuthedIdentitiesIndexRoute: AuthedIdentitiesIndexRoute,
  AuthedOauth2IndexRoute: AuthedOauth2IndexRoute,
  AuthedServiceAccountsIndexRoute: AuthedServiceAccountsIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
