/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TestLoginRouteImport } from './routes/test-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedVaultRouteImport } from './routes/_authed/vault'
import { Route as AuthedRecycleBinRouteImport } from './routes/_authed/recycle-bin'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedSitesIndexRouteImport } from './routes/_authed/sites/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedServiceAccountsIndexRouteImport } from './routes/_authed/service-accounts/index'
import { Route as AuthedSecretsIndexRouteImport } from './routes/_authed/secrets/index'
import { Route as AuthedPlatformIndexRouteImport } from './routes/_authed/platform/index'
import { Route as AuthedOauth2IndexRouteImport } from './routes/_authed/oauth2/index'
import { Route as AuthedIdentitiesIndexRouteImport } from './routes/_authed/identities/index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups/index'
import { Route as AuthedGatewaysIndexRouteImport } from './routes/_authed/gateways/index'
import { Route as AuthedSitesWizardRouteImport } from './routes/_authed/sites/wizard'
import { Route as AuthedSitesCreateRouteImport } from './routes/_authed/sites/create'
import { Route as AuthedSitesSlugRouteImport } from './routes/_authed/sites/$slug'
import { Route as AuthedServiceAccountsCreateRouteImport } from './routes/_authed/service-accounts/create'
import { Route as AuthedServiceAccountsAccountIdRouteImport } from './routes/_authed/service-accounts/$accountId'
import { Route as AuthedOauth2CreateRouteImport } from './routes/_authed/oauth2/create'
import { Route as AuthedOauth2ClientIdRouteImport } from './routes/_authed/oauth2/$clientId'
import { Route as AuthedIntegrationsMentorsAxisRouteImport } from './routes/_authed/integrations/mentors-axis'
import { Route as AuthedIdentitiesImportRouteImport } from './routes/_authed/identities/import'
import { Route as AuthedIdentitiesCreateRouteImport } from './routes/_authed/identities/create'
import { Route as AuthedIdentitiesPersonIdRouteImport } from './routes/_authed/identities/$personId'
import { Route as AuthedGroupsCreateRouteImport } from './routes/_authed/groups/create'
import { Route as AuthedGroupsGroupIdRouteImport } from './routes/_authed/groups/$groupId'
import { Route as ApiUnifiedV1SessionsRouteImport } from './routes/api/unified/v1/sessions'
import { Route as ApiUnifiedV1ConnectionsRouteImport } from './routes/api/unified/v1/connections'
import { Route as AuthedSitesSlugEditRouteImport } from './routes/_authed/sites/$slug.edit'
import { Route as ApiUnifiedV1AuthCallbackRouteImport } from './routes/api/unified/v1/auth/callback'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TestLoginRoute = TestLoginRouteImport.update({
  id: '/test-login',
  path: '/test-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVaultRoute = AuthedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecycleBinRoute = AuthedRecycleBinRouteImport.update({
  id: '/recycle-bin',
  path: '/recycle-bin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSitesIndexRoute = AuthedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServiceAccountsIndexRoute =
  AuthedServiceAccountsIndexRouteImport.update({
    id: '/service-accounts/',
    path: '/service-accounts/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSecretsIndexRoute = AuthedSecretsIndexRouteImport.update({
  id: '/secrets/',
  path: '/secrets/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlatformIndexRoute = AuthedPlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOauth2IndexRoute = AuthedOauth2IndexRouteImport.update({
  id: '/oauth2/',
  path: '/oauth2/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdentitiesIndexRoute = AuthedIdentitiesIndexRouteImport.update({
  id: '/identities/',
  path: '/identities/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGatewaysIndexRoute = AuthedGatewaysIndexRouteImport.update({
  id: '/gateways/',
  path: '/gateways/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSitesWizardRoute = AuthedSitesWizardRouteImport.update({
  id: '/sites/wizard',
  path: '/sites/wizard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSitesCreateRoute = AuthedSitesCreateRouteImport.update({
  id: '/sites/create',
  path: '/sites/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSitesSlugRoute = AuthedSitesSlugRouteImport.update({
  id: '/sites/$slug',
  path: '/sites/$slug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServiceAccountsCreateRoute =
  AuthedServiceAccountsCreateRouteImport.update({
    id: '/service-accounts/create',
    path: '/service-accounts/create',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedServiceAccountsAccountIdRoute =
  AuthedServiceAccountsAccountIdRouteImport.update({
    id: '/service-accounts/$accountId',
    path: '/service-accounts/$accountId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOauth2CreateRoute = AuthedOauth2CreateRouteImport.update({
  id: '/oauth2/create',
  path: '/oauth2/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOauth2ClientIdRoute = AuthedOauth2ClientIdRouteImport.update({
  id: '/oauth2/$clientId',
  path: '/oauth2/$clientId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIntegrationsMentorsAxisRoute =
  AuthedIntegrationsMentorsAxisRouteImport.update({
    id: '/integrations/mentors-axis',
    path: '/integrations/mentors-axis',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedIdentitiesImportRoute = AuthedIdentitiesImportRouteImport.update({
  id: '/identities/import',
  path: '/identities/import',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdentitiesCreateRoute = AuthedIdentitiesCreateRouteImport.update({
  id: '/identities/create',
  path: '/identities/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdentitiesPersonIdRoute =
  AuthedIdentitiesPersonIdRouteImport.update({
    id: '/identities/$personId',
    path: '/identities/$personId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsCreateRoute = AuthedGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsGroupIdRoute = AuthedGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiUnifiedV1SessionsRoute = ApiUnifiedV1SessionsRouteImport.update({
  id: '/api/unified/v1/sessions',
  path: '/api/unified/v1/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnifiedV1ConnectionsRoute = ApiUnifiedV1ConnectionsRouteImport.update({
  id: '/api/unified/v1/connections',
  path: '/api/unified/v1/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSitesSlugEditRoute = AuthedSitesSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthedSitesSlugRoute,
} as any)
const ApiUnifiedV1AuthCallbackRoute =
  ApiUnifiedV1AuthCallbackRouteImport.update({
    id: '/api/unified/v1/auth/callback',
    path: '/api/unified/v1/auth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/test-login': typeof TestLoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/audit': typeof AuthedAuditRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/recycle-bin': typeof AuthedRecycleBinRoute
  '/vault': typeof AuthedVaultRoute
  '/groups/$groupId': typeof AuthedGroupsGroupIdRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/identities/$personId': typeof AuthedIdentitiesPersonIdRoute
  '/identities/create': typeof AuthedIdentitiesCreateRoute
  '/identities/import': typeof AuthedIdentitiesImportRoute
  '/integrations/mentors-axis': typeof AuthedIntegrationsMentorsAxisRoute
  '/oauth2/$clientId': typeof AuthedOauth2ClientIdRoute
  '/oauth2/create': typeof AuthedOauth2CreateRoute
  '/service-accounts/$accountId': typeof AuthedServiceAccountsAccountIdRoute
  '/service-accounts/create': typeof AuthedServiceAccountsCreateRoute
  '/sites/$slug': typeof AuthedSitesSlugRouteWithChildren
  '/sites/create': typeof AuthedSitesCreateRoute
  '/sites/wizard': typeof AuthedSitesWizardRoute
  '/gateways/': typeof AuthedGatewaysIndexRoute
  '/groups/': typeof AuthedGroupsIndexRoute
  '/identities/': typeof AuthedIdentitiesIndexRoute
  '/oauth2/': typeof AuthedOauth2IndexRoute
  '/platform/': typeof AuthedPlatformIndexRoute
  '/secrets/': typeof AuthedSecretsIndexRoute
  '/service-accounts/': typeof AuthedServiceAccountsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/sites/': typeof AuthedSitesIndexRoute
  '/sites/$slug/edit': typeof AuthedSitesSlugEditRoute
  '/api/unified/v1/connections': typeof ApiUnifiedV1ConnectionsRoute
  '/api/unified/v1/sessions': typeof ApiUnifiedV1SessionsRoute
  '/api/unified/v1/auth/callback': typeof ApiUnifiedV1AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/test-login': typeof TestLoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/audit': typeof AuthedAuditRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/recycle-bin': typeof AuthedRecycleBinRoute
  '/vault': typeof AuthedVaultRoute
  '/groups/$groupId': typeof AuthedGroupsGroupIdRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/identities/$personId': typeof AuthedIdentitiesPersonIdRoute
  '/identities/create': typeof AuthedIdentitiesCreateRoute
  '/identities/import': typeof AuthedIdentitiesImportRoute
  '/integrations/mentors-axis': typeof AuthedIntegrationsMentorsAxisRoute
  '/oauth2/$clientId': typeof AuthedOauth2ClientIdRoute
  '/oauth2/create': typeof AuthedOauth2CreateRoute
  '/service-accounts/$accountId': typeof AuthedServiceAccountsAccountIdRoute
  '/service-accounts/create': typeof AuthedServiceAccountsCreateRoute
  '/sites/$slug': typeof AuthedSitesSlugRouteWithChildren
  '/sites/create': typeof AuthedSitesCreateRoute
  '/sites/wizard': typeof AuthedSitesWizardRoute
  '/gateways': typeof AuthedGatewaysIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/identities': typeof AuthedIdentitiesIndexRoute
  '/oauth2': typeof AuthedOauth2IndexRoute
  '/platform': typeof AuthedPlatformIndexRoute
  '/secrets': typeof AuthedSecretsIndexRoute
  '/service-accounts': typeof AuthedServiceAccountsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/sites': typeof AuthedSitesIndexRoute
  '/sites/$slug/edit': typeof AuthedSitesSlugEditRoute
  '/api/unified/v1/connections': typeof ApiUnifiedV1ConnectionsRoute
  '/api/unified/v1/sessions': typeof ApiUnifiedV1SessionsRoute
  '/api/unified/v1/auth/callback': typeof ApiUnifiedV1AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/test-login': typeof TestLoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/recycle-bin': typeof AuthedRecycleBinRoute
  '/_authed/vault': typeof AuthedVaultRoute
  '/_authed/groups/$groupId': typeof AuthedGroupsGroupIdRoute
  '/_authed/groups/create': typeof AuthedGroupsCreateRoute
  '/_authed/identities/$personId': typeof AuthedIdentitiesPersonIdRoute
  '/_authed/identities/create': typeof AuthedIdentitiesCreateRoute
  '/_authed/identities/import': typeof AuthedIdentitiesImportRoute
  '/_authed/integrations/mentors-axis': typeof AuthedIntegrationsMentorsAxisRoute
  '/_authed/oauth2/$clientId': typeof AuthedOauth2ClientIdRoute
  '/_authed/oauth2/create': typeof AuthedOauth2CreateRoute
  '/_authed/service-accounts/$accountId': typeof AuthedServiceAccountsAccountIdRoute
  '/_authed/service-accounts/create': typeof AuthedServiceAccountsCreateRoute
  '/_authed/sites/$slug': typeof AuthedSitesSlugRouteWithChildren
  '/_authed/sites/create': typeof AuthedSitesCreateRoute
  '/_authed/sites/wizard': typeof AuthedSitesWizardRoute
  '/_authed/gateways/': typeof AuthedGatewaysIndexRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/identities/': typeof AuthedIdentitiesIndexRoute
  '/_authed/oauth2/': typeof AuthedOauth2IndexRoute
  '/_authed/platform/': typeof AuthedPlatformIndexRoute
  '/_authed/secrets/': typeof AuthedSecretsIndexRoute
  '/_authed/service-accounts/': typeof AuthedServiceAccountsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/sites/': typeof AuthedSitesIndexRoute
  '/_authed/sites/$slug/edit': typeof AuthedSitesSlugEditRoute
  '/api/unified/v1/connections': typeof ApiUnifiedV1ConnectionsRoute
  '/api/unified/v1/sessions': typeof ApiUnifiedV1SessionsRoute
  '/api/unified/v1/auth/callback': typeof ApiUnifiedV1AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/test-login'
    | '/unauthorized'
    | '/audit'
    | '/dashboard'
    | '/recycle-bin'
    | '/vault'
    | '/groups/$groupId'
    | '/groups/create'
    | '/identities/$personId'
    | '/identities/create'
    | '/identities/import'
    | '/integrations/mentors-axis'
    | '/oauth2/$clientId'
    | '/oauth2/create'
    | '/service-accounts/$accountId'
    | '/service-accounts/create'
    | '/sites/$slug'
    | '/sites/create'
    | '/sites/wizard'
    | '/gateways/'
    | '/groups/'
    | '/identities/'
    | '/oauth2/'
    | '/platform/'
    | '/secrets/'
    | '/service-accounts/'
    | '/settings/'
    | '/sites/'
    | '/sites/$slug/edit'
    | '/api/unified/v1/connections'
    | '/api/unified/v1/sessions'
    | '/api/unified/v1/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/test-login'
    | '/unauthorized'
    | '/audit'
    | '/dashboard'
    | '/recycle-bin'
    | '/vault'
    | '/groups/$groupId'
    | '/groups/create'
    | '/identities/$personId'
    | '/identities/create'
    | '/identities/import'
    | '/integrations/mentors-axis'
    | '/oauth2/$clientId'
    | '/oauth2/create'
    | '/service-accounts/$accountId'
    | '/service-accounts/create'
    | '/sites/$slug'
    | '/sites/create'
    | '/sites/wizard'
    | '/gateways'
    | '/groups'
    | '/identities'
    | '/oauth2'
    | '/platform'
    | '/secrets'
    | '/service-accounts'
    | '/settings'
    | '/sites'
    | '/sites/$slug/edit'
    | '/api/unified/v1/connections'
    | '/api/unified/v1/sessions'
    | '/api/unified/v1/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/callback'
    | '/login'
    | '/test-login'
    | '/unauthorized'
    | '/_authed/audit'
    | '/_authed/dashboard'
    | '/_authed/recycle-bin'
    | '/_authed/vault'
    | '/_authed/groups/$groupId'
    | '/_authed/groups/create'
    | '/_authed/identities/$personId'
    | '/_authed/identities/create'
    | '/_authed/identities/import'
    | '/_authed/integrations/mentors-axis'
    | '/_authed/oauth2/$clientId'
    | '/_authed/oauth2/create'
    | '/_authed/service-accounts/$accountId'
    | '/_authed/service-accounts/create'
    | '/_authed/sites/$slug'
    | '/_authed/sites/create'
    | '/_authed/sites/wizard'
    | '/_authed/gateways/'
    | '/_authed/groups/'
    | '/_authed/identities/'
    | '/_authed/oauth2/'
    | '/_authed/platform/'
    | '/_authed/secrets/'
    | '/_authed/service-accounts/'
    | '/_authed/settings/'
    | '/_authed/sites/'
    | '/_authed/sites/$slug/edit'
    | '/api/unified/v1/connections'
    | '/api/unified/v1/sessions'
    | '/api/unified/v1/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  TestLoginRoute: typeof TestLoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiUnifiedV1ConnectionsRoute: typeof ApiUnifiedV1ConnectionsRoute
  ApiUnifiedV1SessionsRoute: typeof ApiUnifiedV1SessionsRoute
  ApiUnifiedV1AuthCallbackRoute: typeof ApiUnifiedV1AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-login': {
      id: '/test-login'
      path: '/test-login'
      fullPath: '/test-login'
      preLoaderRoute: typeof TestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/vault': {
      id: '/_authed/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthedVaultRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recycle-bin': {
      id: '/_authed/recycle-bin'
      path: '/recycle-bin'
      fullPath: '/recycle-bin'
      preLoaderRoute: typeof AuthedRecycleBinRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sites/': {
      id: '/_authed/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthedSitesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/service-accounts/': {
      id: '/_authed/service-accounts/'
      path: '/service-accounts'
      fullPath: '/service-accounts/'
      preLoaderRoute: typeof AuthedServiceAccountsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/secrets/': {
      id: '/_authed/secrets/'
      path: '/secrets'
      fullPath: '/secrets/'
      preLoaderRoute: typeof AuthedSecretsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/platform/': {
      id: '/_authed/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthedPlatformIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oauth2/': {
      id: '/_authed/oauth2/'
      path: '/oauth2'
      fullPath: '/oauth2/'
      preLoaderRoute: typeof AuthedOauth2IndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/identities/': {
      id: '/_authed/identities/'
      path: '/identities'
      fullPath: '/identities/'
      preLoaderRoute: typeof AuthedIdentitiesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/gateways/': {
      id: '/_authed/gateways/'
      path: '/gateways'
      fullPath: '/gateways/'
      preLoaderRoute: typeof AuthedGatewaysIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sites/wizard': {
      id: '/_authed/sites/wizard'
      path: '/sites/wizard'
      fullPath: '/sites/wizard'
      preLoaderRoute: typeof AuthedSitesWizardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sites/create': {
      id: '/_authed/sites/create'
      path: '/sites/create'
      fullPath: '/sites/create'
      preLoaderRoute: typeof AuthedSitesCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sites/$slug': {
      id: '/_authed/sites/$slug'
      path: '/sites/$slug'
      fullPath: '/sites/$slug'
      preLoaderRoute: typeof AuthedSitesSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/service-accounts/create': {
      id: '/_authed/service-accounts/create'
      path: '/service-accounts/create'
      fullPath: '/service-accounts/create'
      preLoaderRoute: typeof AuthedServiceAccountsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/service-accounts/$accountId': {
      id: '/_authed/service-accounts/$accountId'
      path: '/service-accounts/$accountId'
      fullPath: '/service-accounts/$accountId'
      preLoaderRoute: typeof AuthedServiceAccountsAccountIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oauth2/create': {
      id: '/_authed/oauth2/create'
      path: '/oauth2/create'
      fullPath: '/oauth2/create'
      preLoaderRoute: typeof AuthedOauth2CreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/oauth2/$clientId': {
      id: '/_authed/oauth2/$clientId'
      path: '/oauth2/$clientId'
      fullPath: '/oauth2/$clientId'
      preLoaderRoute: typeof AuthedOauth2ClientIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/integrations/mentors-axis': {
      id: '/_authed/integrations/mentors-axis'
      path: '/integrations/mentors-axis'
      fullPath: '/integrations/mentors-axis'
      preLoaderRoute: typeof AuthedIntegrationsMentorsAxisRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/identities/import': {
      id: '/_authed/identities/import'
      path: '/identities/import'
      fullPath: '/identities/import'
      preLoaderRoute: typeof AuthedIdentitiesImportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/identities/create': {
      id: '/_authed/identities/create'
      path: '/identities/create'
      fullPath: '/identities/create'
      preLoaderRoute: typeof AuthedIdentitiesCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/identities/$personId': {
      id: '/_authed/identities/$personId'
      path: '/identities/$personId'
      fullPath: '/identities/$personId'
      preLoaderRoute: typeof AuthedIdentitiesPersonIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/create': {
      id: '/_authed/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AuthedGroupsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$groupId': {
      id: '/_authed/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthedGroupsGroupIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/unified/v1/sessions': {
      id: '/api/unified/v1/sessions'
      path: '/api/unified/v1/sessions'
      fullPath: '/api/unified/v1/sessions'
      preLoaderRoute: typeof ApiUnifiedV1SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unified/v1/connections': {
      id: '/api/unified/v1/connections'
      path: '/api/unified/v1/connections'
      fullPath: '/api/unified/v1/connections'
      preLoaderRoute: typeof ApiUnifiedV1ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/sites/$slug/edit': {
      id: '/_authed/sites/$slug/edit'
      path: '/edit'
      fullPath: '/sites/$slug/edit'
      preLoaderRoute: typeof AuthedSitesSlugEditRouteImport
      parentRoute: typeof AuthedSitesSlugRoute
    }
    '/api/unified/v1/auth/callback': {
      id: '/api/unified/v1/auth/callback'
      path: '/api/unified/v1/auth/callback'
      fullPath: '/api/unified/v1/auth/callback'
      preLoaderRoute: typeof ApiUnifiedV1AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedSitesSlugRouteChildren {
  AuthedSitesSlugEditRoute: typeof AuthedSitesSlugEditRoute
}

const AuthedSitesSlugRouteChildren: AuthedSitesSlugRouteChildren = {
  AuthedSitesSlugEditRoute: AuthedSitesSlugEditRoute,
}

const AuthedSitesSlugRouteWithChildren = AuthedSitesSlugRoute._addFileChildren(
  AuthedSitesSlugRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedRecycleBinRoute: typeof AuthedRecycleBinRoute
  AuthedVaultRoute: typeof AuthedVaultRoute
  AuthedGroupsGroupIdRoute: typeof AuthedGroupsGroupIdRoute
  AuthedGroupsCreateRoute: typeof AuthedGroupsCreateRoute
  AuthedIdentitiesPersonIdRoute: typeof AuthedIdentitiesPersonIdRoute
  AuthedIdentitiesCreateRoute: typeof AuthedIdentitiesCreateRoute
  AuthedIdentitiesImportRoute: typeof AuthedIdentitiesImportRoute
  AuthedIntegrationsMentorsAxisRoute: typeof AuthedIntegrationsMentorsAxisRoute
  AuthedOauth2ClientIdRoute: typeof AuthedOauth2ClientIdRoute
  AuthedOauth2CreateRoute: typeof AuthedOauth2CreateRoute
  AuthedServiceAccountsAccountIdRoute: typeof AuthedServiceAccountsAccountIdRoute
  AuthedServiceAccountsCreateRoute: typeof AuthedServiceAccountsCreateRoute
  AuthedSitesSlugRoute: typeof AuthedSitesSlugRouteWithChildren
  AuthedSitesCreateRoute: typeof AuthedSitesCreateRoute
  AuthedSitesWizardRoute: typeof AuthedSitesWizardRoute
  AuthedGatewaysIndexRoute: typeof AuthedGatewaysIndexRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
  AuthedIdentitiesIndexRoute: typeof AuthedIdentitiesIndexRoute
  AuthedOauth2IndexRoute: typeof AuthedOauth2IndexRoute
  AuthedPlatformIndexRoute: typeof AuthedPlatformIndexRoute
  AuthedSecretsIndexRoute: typeof AuthedSecretsIndexRoute
  AuthedServiceAccountsIndexRoute: typeof AuthedServiceAccountsIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSitesIndexRoute: typeof AuthedSitesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedRecycleBinRoute: AuthedRecycleBinRoute,
  AuthedVaultRoute: AuthedVaultRoute,
  AuthedGroupsGroupIdRoute: AuthedGroupsGroupIdRoute,
  AuthedGroupsCreateRoute: AuthedGroupsCreateRoute,
  AuthedIdentitiesPersonIdRoute: AuthedIdentitiesPersonIdRoute,
  AuthedIdentitiesCreateRoute: AuthedIdentitiesCreateRoute,
  AuthedIdentitiesImportRoute: AuthedIdentitiesImportRoute,
  AuthedIntegrationsMentorsAxisRoute: AuthedIntegrationsMentorsAxisRoute,
  AuthedOauth2ClientIdRoute: AuthedOauth2ClientIdRoute,
  AuthedOauth2CreateRoute: AuthedOauth2CreateRoute,
  AuthedServiceAccountsAccountIdRoute: AuthedServiceAccountsAccountIdRoute,
  AuthedServiceAccountsCreateRoute: AuthedServiceAccountsCreateRoute,
  AuthedSitesSlugRoute: AuthedSitesSlugRouteWithChildren,
  AuthedSitesCreateRoute: AuthedSitesCreateRoute,
  AuthedSitesWizardRoute: AuthedSitesWizardRoute,
  AuthedGatewaysIndexRoute: AuthedGatewaysIndexRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
  AuthedIdentitiesIndexRoute: AuthedIdentitiesIndexRoute,
  AuthedOauth2IndexRoute: AuthedOauth2IndexRoute,
  AuthedPlatformIndexRoute: AuthedPlatformIndexRoute,
  AuthedSecretsIndexRoute: AuthedSecretsIndexRoute,
  AuthedServiceAccountsIndexRoute: AuthedServiceAccountsIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSitesIndexRoute: AuthedSitesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  TestLoginRoute: TestLoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiUnifiedV1ConnectionsRoute: ApiUnifiedV1ConnectionsRoute,
  ApiUnifiedV1SessionsRoute: ApiUnifiedV1SessionsRoute,
  ApiUnifiedV1AuthCallbackRoute: ApiUnifiedV1AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
